//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoriaClinica
    {
        public int Id { get; set; }
        public string Odontograma { get; set; }
        public int NumeroCariados { get; set; }
        public int NumeroDientesPerdidos { get; set; }
        public int NumeroDientesObturados { get; set; }
        public string Ortodoncia { get; set; }
        public string Protesis { get; set; }
        public int Implantes { get; set; }
        public int ParesAntagPerdidos { get; set; }
        public int GradoEdentulismo { get; set; }
        public bool EstadoSaludGeneral { get; set; }
        public bool EnfermedadCardioVascular { get; set; }
        public bool EnfermedadRenal { get; set; }
        public bool ICTUS { get; set; }
        public bool ACV { get; set; }
        public bool ParalisisFacial { get; set; }
        public int GradoDesnutricion { get; set; }
        public int IdPaciente { get; set; }
    
        public virtual Paciente Paciente { get; set; }
    }
}
