//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Imagenes
    {
        public int Id { get; set; }
        public int NumeroCiclos { get; set; }
        public int NumeroToma { get; set; }
        public int Cara { get; set; }
        public int IdPaciente { get; set; }
        public int IdMPAT { get; set; }
    
        public virtual Paciente Paciente { get; set; }
        public virtual MPAT MPAT { get; set; }
    }
}
