//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class MPAT
    {
        public MPAT()
        {
            this.Imagenes = new HashSet<Imagenes>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public string WikiURL { get; set; }
        public string AlimentoPrueba { get; set; }
    
        public virtual ICollection<Imagenes> Imagenes { get; set; }
    }
}
